### PR TITLE
update ws dep

### LINKED ISSUE #4: tests failure
Hi! suddenly tests starts falling.

```
1) wamp Should create two clients, make RPC and pub / sub:
     Uncaught TypeError: Cannot read property 'mask' of undefined
      at Sender.frameAndSend (node_modules/ws/lib/Sender.js:206:17)
      at node_modules/ws/lib/Sender.js:126:12
      at node_modules/ws/lib/PerMessageDeflate.js:313:5
      at afterWrite (_stream_writable.js:386:3)
      at onwrite (_stream_writable.js:377:7)
      at afterTransform (_stream_transform.js:79:3)
      at TransformState.afterTransform (_stream_transform.js:54:12)
      at Zlib.callback (zlib.js:625:5)
```

### PR DESCRIPTION
**Pull request by tyv**
fixes #4

### CODE REVIEW

**Comment by ivaylopivanov** [comment]
Thansk @tyv. Will fix the CI and will publish the new version.

**Comment by tyv** [comment]
@ivaylopivanov sorry I missed also one more update, you have to update autobahn to `"^0.11.2"`

**Comment by ivaylopivanov** [comment]
@tyv done. 0.0.6 published.

**Comment by tyv** [comment]
many thanks! 🎉

**Pull request merged**
